/* Generated By:JavaCC: Do not edit this line. MiniLispConstants.java */
package com.threelambda.minilisp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniLispConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EMPTY = 1;
  /** RegularExpression Id. */
  int LP = 2;
  /** RegularExpression Id. */
  int RP = 3;
  /** RegularExpression Id. */
  int DOT = 4;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int EQ = 7;
  /** RegularExpression Id. */
  int GT = 8;
  /** RegularExpression Id. */
  int LT = 9;
  /** RegularExpression Id. */
  int LE = 10;
  /** RegularExpression Id. */
  int GE = 11;
  /** RegularExpression Id. */
  int SQUOTE = 12;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int COMMENT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EMPTY>",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"-\"",
    "\"+\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"\\\'\"",
    "<NUM>",
    "<ID>",
    "<COMMENT>",
  };

}
